baseurl = "https://delonshenblog.netlify.com/"
languageCode = "en-us"
title = "delon shen"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 3
[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "delon shen"
    footer = "[github](https://github.com/delonshen) | [email](mailto:hi@delonshen.com)"
    custom_css = ["css/theme-override.css"]
